config/routes.rb
Rails.application.routes.draw do
  resources :alumnis
  devise_for :users
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
 end
  resources :friends
  #get 'home/index'
  root 'home#index'
  get 'home/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  

end

app/models/alumni.rb
class Alumni < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
 belongs_to :user
 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends
end

app/controllers/alumnis_controller.rb
class AlumnisController < ApplicationController
  before_action :set_alumni, only: [:show, :edit, :update, :destroy]

  # GET /alumnis
  # GET /alumnis.json
  def index
    @alumnis = Alumni.all
  end

  # GET /alumnis/1
  # GET /alumnis/1.json
  def show
  end

  # GET /alumnis/new
  def new
    @alumni = Alumni.new
  end

  # GET /alumnis/1/edit
  def edit
  end

  # POST /alumnis
  # POST /alumnis.json
  def create
    @alumni = Alumni.new(alumni_params)

    respond_to do |format|
      if @alumni.save
        format.html { redirect_to @alumni, notice: 'Alumni was successfully created.' }
        format.json { render :show, status: :created, location: @alumni }
      else
        format.html { render :new }
        format.json { render json: @alumni.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alumnis/1
  # PATCH/PUT /alumnis/1.json
  def update
    respond_to do |format|
      if @alumni.update(alumni_params)
        format.html { redirect_to @alumni, notice: 'Alumni was successfully updated.' }
        format.json { render :show, status: :ok, location: @alumni }
      else
        format.html { render :edit }
        format.json { render json: @alumni.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alumnis/1
  # DELETE /alumnis/1.json
  def destroy
    @alumni.destroy
    respond_to do |format|
      format.html { redirect_to alumnis_url, notice: 'Alumni was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alumni
      @alumni = Alumni.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def alumni_params
      params.require(:alumni).permit(:first_name, :last_name, :email, :program)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: [:show, :edit, :update, :destroy]

  # GET /friends
  # GET /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1
  # GET /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends
  # POST /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: 'Friend was successfully created.' }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1
  # PATCH/PUT /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: 'Friend was successfully updated.' }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1
  # DELETE /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: 'Friend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about 
  end
  
end

app/helpers/alumnis_helper.rb
module AlumnisHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/alumnis/_form.html.erb
<%= form_with(model: alumni, local: true) do |form| %>
  <% if alumni.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(alumni.errors.count, "error") %> prohibited this alumni from being saved:</h2>

      <ul>
        <% alumni.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :program %>
    <%= form.text_field :program %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/alumnis/edit.html.erb
<h1>Editing Alumni</h1>

<%= render 'form', alumni: @alumni %>

<%= link_to 'Show', @alumni %> |
<%= link_to 'Back', alumnis_path %>

app/views/alumnis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alumnis</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Program</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alumnis.each do |alumni| %>
      <tr>
        <td><%= alumni.first_name %></td>
        <td><%= alumni.last_name %></td>
        <td><%= alumni.email %></td>
        <td><%= alumni.program %></td>
        <td><%= link_to 'Show', alumni %></td>
        <td><%= link_to 'Edit', edit_alumni_path(alumni) %></td>
        <td><%= link_to 'Destroy', alumni_path(alumni), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alumni', new_alumni_path %>

app/views/alumnis/new.html.erb
<h1>New Alumni</h1>

<%= render 'form', alumni: @alumni %>

<%= link_to 'Back', alumnis_path %>

app/views/alumnis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @alumni.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @alumni.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @alumni.email %>
</p>

<p>
  <strong>Program:</strong>
  <%= @alumni.program %>
</p>

<%= link_to 'Edit', edit_alumni_path(@alumni) %> |
<%= link_to 'Back', alumnis_path %>

app/views/friends/_form.html.erb
<%= form_with(model: friend, local: true) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <% form.label :first_name %>
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>
  <br>
  <div class="field form-group">
    <% form.label :last_name %>
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
  </div>
  <br>
  <div class="field form-group">
    <% form.label :email %>
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div>
  <br>
  <div class="field form-group">
    <% form.label :phone %>
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone" %>
  </div>
  <br>
  <div class="field form-group">
    <% form.label :twitter %>
    <%= form.text_field :twitter, class:"form-control", placeholder:"Twitter" %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit class:'btn btn-secondary' %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>
<br>
<%= render 'form', friend: @friend %>
<br>
<%= link_to 'Show', @friend, class:"btn btn-secondary" %> 
<%= link_to 'Back', friends_path, class:"btn btn-dark" %>

app/views/friends/index.html.erb
<br>
<table class="table table-bordered table-striped table-hover">
  <thead class="thead-dark">
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Twitter</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friends.each do |friend| %>
      <tr>
        <td><%= friend.first_name %></td>
        <td><%= friend.last_name %></td>
        <td><%= friend.email %></td>
        <td><%= friend.phone %></td>
        <td><%= friend.twitter %></td>
        <td><%= link_to 'Show', friend %></td>
        <td><%= link_to 'Edit', edit_friend_path(friend) %></td>
        <td><%= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friend', new_friend_path, class:"btn btn-secondary" %>

app/views/friends/new.html.erb
<h1>Add New Friend</h1>
<br>
<%= render 'form', friend: @friend %>
<br>
<%= link_to 'Back', friends_path, class:"btn btn-dark" %>

app/views/friends/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= @friend.first_name %>
  <%= @friend.last_name %></h1>
  <br>
  <p class="lead">
  <%= @friend.email %>|
  <%= @friend.phone %>|
  <%= @friend.twitter %>
  </p>
  <br>
  
  
  <%= link_to 'Edit', edit_friend_path(@friend), class:"btn btn-secondary" %> 
  <%= link_to 'Back', friends_path, class:"btn btn-dark" %>

 
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 48 48"><title>multiple-11</title><g><circle fill="#9BCED3" cx="39" cy="10" r="5"></circle> <circle fill="#9BCED3" cx="9" cy="10" r="5"></circle> <path fill-rule="evenodd" clip-rule="evenodd" fill="#76B5B5" d="M35.9966888,17C33.2370911,17,31,19.2295895,31,22.0038109 v6.7917995c0,0.5547104,0.4171391,1.1712494,0.9327698,1.3774986L34,31l0.9164581,10.9975281 C34.9626007,42.551178,35.4530411,43,35.9970284,43h6.0059433c0.5506401,0,1.0350075-0.455761,1.0805702-1.0024719L44,31 l2.0507812-0.6835899C46.5750198,30.1416607,47,29.5525093,47,29.0014992v-6.9939594C47,19.2419491,44.758419,17,42.0033112,17 H35.9966888z"></path> <path fill-rule="evenodd" clip-rule="evenodd" fill="#76B5B5" d="M5.996686,17C3.237092,17,1,19.2295895,1,22.0038109v6.7917995 c0,0.5547104,0.4171371,1.1712494,0.9327741,1.3774986L4,31l0.916461,10.9975281C4.9625978,42.551178,5.4530358,43,5.9970298,43 h6.00594c0.5506401,0,1.0350103-0.455761,1.0805702-1.0024719L14,31l2.0507812-0.6835899 C16.5750198,30.1416607,17,29.5525093,17,29.0014992v-6.9939594C17,19.2419491,14.75842,17,12.0033102,17H5.996686z"></path> <circle fill="#5A7A84" cx="24" cy="7" r="6"></circle> <path fill-rule="evenodd" clip-rule="evenodd" fill="#335262" d="M20.0006599,15C16.6865902,15,14,17.6780396,14,21.0033302v8.9958 c0,0.5527592,0.39816,1.1999512,0.8877296,1.4447289L18,33l1.0039997,13.0830002C19.0470009,46.6020012,19.4790001,47,20,47h8 c0.5209999,0,0.9529991-0.3979988,0.9960003-0.9169998l0.941-13.2870026l3.1410408-1.3884583 C33.5872307,31.1824608,34,30.5553703,34,29.9991302v-8.9958C34,17.6877804,31.3234596,15,27.9993401,15H20.0006599z"></path></g></svg>
    <%= link_to 'Friends App', root_path, class:"navbar-brand"  %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <li class="nav-item">
          <%= link_to 'About Us', home_about_path, class:"nav-link"  %>
        </li>
        
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Friends List', friends_path, class:"nav-link"  %>
        </li>
        <li class="nav-item">
          <%= link_to 'Add Friend', new_friend_path, class:"nav-link"  %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link"   %>
        </li>
        <li class="nav-item">
          <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link"  %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link"  %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_path, class:"nav-link"  %>
        </li>
        <% end %>
        
        
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About us </h1>

app/views/home/index.html.erb
<h1>Friends App</h1>
<p>You are going to love this rails app...</p>

app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>Friends App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     
    <%
=begin%>
 <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %> 
<%
=end%>
     
 <%= javascript_tag 'application', 'data-turbolinks-track': 'reload' %> 


  </head>
  <body>

   <%= render 'home/header' %>
   <div class="container">
   <% if notice %>
    <%= render 'layouts/alert' %>
   <% end %>

   <br>
    <%= yield %>
   </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>